# Pull gems from RubyGems
source 'https://rubygems.org'

# ~> Refers to all versions of the given gem on the current full version number. For a specific version of a gem, remove the ~>
gem 'chunky_png', '~>1.2'
gem 'compass', '1.0.3'
gem 'compass-notify', '0.0.2'
gem 'compass-rgbapng', '0.2.1'
gem 'fssm', '0.2.10'
gem 'oily_png', '1.1'
gem 'sass', '3.4'
gem 'susy', '1.0'
gem 'terminal-notifier', '1.6'

# Now that you're using Bundler, you need to run `bundle exec compass watch` instead of simply `compass watch`.
