<?php

/**
 * @file
 * Dimpact MY-LEX Overheid zoekform blok module file
 *
 * This module adds a block with a search form to MY-LEX Overheid by C-Content.
 */

/**
 * Implements hook_help().
 */
function dimpact_mylex_help($path, $arg) {
  if ($path == 'admin/help#dimpact_mylex') {
    return t('The Dimpact MY-LEX Overheid zoekform blok module adds a block with a search form to MY-LEX Overheid by C-Content.');
  }
}

/**
 * Implements hook_block_info().
 */
function dimpact_mylex_block_info() {
  $blocks = array();
  $blocks['dimpact_mylex_search'] = array(
    'info' => t('MY-LEX Overheid searchbox'),
  );
  return $blocks;
}
