<?php

/**
 * @file
 */

define('CUSTOM_CSS_PATH', 'public://custom_css');

/**
 * Implements hook_menu().
 */
function dimpact_custom_css_menu() {
  return array('admin/appearance/css' => array(
    'title' => t('Custom CSS'),
    'description' => t('Uploading custom CSS files.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dimpact_custom_css_upload'),
    'access arguments' => array('administer custom css files'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'dimpact_custom_css.admin.inc',
  ));
}

/**
 * Implements hook_permission().
 */
function dimpact_custom_css_permission() {
  return array(
    'administer custom css files' => array(
      'title' => t('Administer custom CSS files'),
      'description' => t('Add custom CSS files to your theme.'),
    ),
  );
}

/**
 * Implements hook_form_alter().
 *
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function dimpact_custom_css_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'file_entity_add_upload') {
    $form['description'] = array(
      '#type' => 'markup',
      '#markup' => t('Please note, make sure you have a license for using the uploaded webfonts'),
      '#prefix' => '<div><strong>',
      '#suffix' => '</strong></div>',
    );
  }
}

/**
 * Helper function for returning the default custom_css files.
 */
function dimpact_custom_css_files() {
  return array(
    'custom_css_screen' => t('CSS Screen'),
    'custom_css_print'  => t('CSS Print'),
    'custom_css_lteie9' => t('CSS LTE IE9'),
    'custom_css_ltie9'  => t('CSS LT IE9'),
  );
}

/**
 * Helper function for returning the current domain.
 */
function _dimpact_custom_css_domainid() {
  global $_domain;
  return $_domain['domain_id'];
}
