<?php
/**
 * Implements hook_gvop_info().
 */
function gvop_cvdr_gvop_info() {
  return array(
    'cvdr' => array(
      'type' => 'cvdr',
      'callback' => 'gvop_cvdr_map',
      'query' => array(
        'type' => 'regeling',
      )
    ),
  );
}

/**
 * Callback for mapping gvop cvdr nodes.
 *
 * @param DOMElement $record
 * @param $node
 * @param DOMXPath $xpath
 */
function gvop_cvdr_map(DOMElement $record, $node, DOMXPath $xpath) {
  $node->type = 'regulation';

  // Date fields.
  if (($issuedNode = $xpath->query('.//dcterms:issued', $record)->item(0)) && trim($issuedNode->nodeValue) != '') {
    $node->field_reg_issued = array(
      LANGUAGE_NONE => array(array('value' => $issuedNode->nodeValue))
    );
  }

  // Text fields.
  if (($introNode = $xpath->query('.//dcterms:subject', $record)->item(0)) && !empty($introNode->nodeValue)) {
    $node->field_intro = array(
      LANGUAGE_NONE => array(array('value' => $introNode->nodeValue))
    );
  }
  $node->field_ratified_by = array(
    LANGUAGE_NONE => array(array('value' => $xpath->query('.//dcterms:isRatifiedBy', $record)->item(0)->nodeValue))
  );
  $node->field_reg_concerning = array(
    LANGUAGE_NONE => array(array('value' => $xpath->query('.//overheidrg:betreft', $record)->item(0)->nodeValue))
  );
  $node->field_reg_characteristic = array(
    LANGUAGE_NONE => array(array('value' => $xpath->query('.//overheidrg:kenmerk', $record)->item(0)->nodeValue))
  );
  $node->field_reg_subject = array(
    LANGUAGE_NONE => array(array('value' => $xpath->query('.//overheidrg:onderwerp', $record)->item(0)->nodeValue))
  );

  // Text fields with format.
  $node->field_red_addition = array(
    LANGUAGE_NONE => array(
      array(
        'value' => $xpath->query('.//overheidrg:redactioneleToevoeging', $record)->item(0)->nodeValue,
        'format' => 'filtered_html',
      )
    )
  );

  if (module_exists('scheduler')) {
    $publish_on_str = $xpath->query('.//overheidrg:inwerkingtredingDatum', $record)->item(0)->nodeValue;
    if (!empty($publish_on_str)) {
      $node->publish_on =  strtotime($publish_on_str);
    }

    $unpublish_on_str = $xpath->query('.//overheidrg:uitwerkingtredingDatum', $record)->item(0)->nodeValue;
    if (!empty($unpublish_on_str)) {
      $node->unpublish_on = strtotime($unpublish_on_str);
    }
  }

  $xpath->registerNamespace('ns1', "http://standaarden.overheid.nl/sru");
  $pubUrl = $xpath->query('.//ns1:publicatieurl_xml', $record)->item(0)->nodeValue;
  if ($pubUrl) {
    $pubXML = file_get_contents($pubUrl);
    if ($pubXML) {
      $pubDOM = new DOMDocument;
      $pubDOM->loadXML($pubXML);
      $regeling = $pubDOM->getElementsByTagName('regeling')->item(0);
      $body_str = _gvop_cvdr_xml_read_text($regeling);

      $node->body = array(
        LANGUAGE_NONE => array(
          array(
            'value' => $body_str,
            'format' => 'filtered_html',
          )
        )
      );
    }
  }
}

function _gvop_cvdr_xml_read_text(DOMElement $element, $level = 1) {
  $output = '';
  if (!$element->hasChildNodes()) {
    return $output;
  }
  $child = $element->firstChild;
  do {
    if ($child instanceof DOMText) {
      $output .= htmlentities($child->nodeValue, ENT_COMPAT, 'UTF-8');
    }
    if ($child instanceof DOMElement) {
      switch ($child->tagName) {
        case 'intitule':
          // Currently no implementation.
          break;
        case 'aanhef':
        case 'preambule':
        case 'regeling-tekst':
        case 'hoofdstuk':
          $output .= _gvop_cvdr_xml_read_text($child, $level);
          break;
        case 'artikel':
          $output .= _gvop_cvdr_xml_read_text($child, $level + 1);
          break;
        case 'al':
          $output .= '<p>';
          $output .= _gvop_cvdr_xml_read_text($child, $level);
          $output .= '</p>';
          break;
        case 'vet':
          $output .= '<strong>';
          $output .= _gvop_cvdr_xml_read_text($child, $level);
          $output .= '</strong>';
          break;
        case 'sup':
          $output .= '<span class="sup">';
          $output .= _gvop_cvdr_xml_read_text($child, $level);
          $output .= '</span>';
          break;
        case 'kop':
          $output .= _gvop_cvdr_xml_read_kop($child, 'h' . ($level + 1));
          break;
        case 'tussenkop':
          $output .= _gvop_cvdr_xml_read_kop($child, 'h' . ($level + 2));
          break;
        case 'lijst':
          $output .= _gvop_cvdr_xml_read_lijst($child);
          break;
        case 'lid':
          $output .= _gvop_cvdr_xml_read_lid($child);
          break;
      }
    }
    $output .= PHP_EOL;
  } while ($child = $child->nextSibling);
  return $output;
}

function _gvop_cvdr_xml_read_kop(DOMElement $element, $tag = 'h2') {
  $output = '';
  if (!$element->hasChildNodes()) {
    return $output;
  }
  $child = $element->firstChild;
  do {
    if (!$child instanceof DOMElement) {
      continue;
    }
    ${$child->tagName} = trim(htmlentities($child->nodeValue, ENT_COMPAT, 'UTF-8'));
  } while ($child = $child->nextSibling);

  // Tag, Label, Nr, Titel are dynamically set so this might give errors in
  // your IDE.
  $output .= '<' . $tag . '>';
  $output .= empty($label) ? '' : "$label ";
  $output .= empty($nr) ? '' : "$nr ";
  $output .= $titel;
  $output .= '</' . $tag . '>';

  return $output;
}

function _gvop_cvdr_xml_read_lijst(DOMElement $element) {
  $output = '';
  if (!$element->hasChildNodes()) {
    return $output;
  }
  $output .= '<ul class="whitespace-small">';
  $child = $element->firstChild;
  do {
    if (!$child instanceof DOMElement) {
      continue;
    }
    $output .= '<li>';
    $nr = $child->getAttribute('nr');
    $text = trim(_gvop_cvdr_xml_read_text($child));
    if (!empty($nr)) {
      $nr = $nr == '-' ? '·' : $nr;
      $nr = '<span class="ol">' . htmlentities($nr, ENT_COMPAT, 'UTF-8') . ' </span>';
      if (preg_match('/^\\<p\\>/s', $text)) {
        $text = preg_replace('/^\\<p\\>/s', '<p>' . $nr, $text);
      }
      else {
        $text = $nr . $text;
      }
      if (preg_match('/^\\<p\\>(.*)\\<\\/p\\>$/si', $text, $match)) {
        $text = $match[1];
      }
    }
    $output .= $text;
    $output .= '</li>';
  } while ($child = $child->nextSibling);
  $output .= '</ul>';
  return $output;
}

function _gvop_cvdr_xml_read_lid(DOMElement $element) {
  $output = '';
  if (!$element->hasChildNodes()) {
    return $output;
  }
  $child = $element->firstChild;
  do {
    if (!$child instanceof DOMElement) {
      continue;
    }
    if ($child->tagName == 'lidnr') {
      $lidnr = $child->nodeValue;
    }
  } while ($child = $child->nextSibling);
  $text = _gvop_cvdr_xml_read_text($element);
  if (!empty($lidnr)) {
    $lidnr = htmlentities($lidnr, ENT_COMPAT, 'UTF-8');
    $lidnr = '<span class="lidnr">' . $lidnr . ' </span>';
    if (preg_match('/^\\<p\\>/s', $text)) {
      $text = preg_replace('/^\\<p\\>/s', '<p>' . $lidnr, $text);
    }
    else {
      $text = $lidnr . $text;
    }
  }
  $output .= $text;
  return $output;
}