<?php
/**
 * Implements hook_gvop_info().
 */
function gvop_cvdr_gvop_info() {
  return array(
    'cvdr' => array(
      'type' => 'cvdr',
      'callback' => 'gvop_cvdr_map',
      'query' => array(
        'type' => 'regeling',
      )
    ),
  );
}

/**
 * Callback for mapping gvop cvdr nodes.
 *
 * @param DOMElement $record
 * @param $node
 * @param DOMXPath $xpath
 */
function gvop_cvdr_map(DOMElement $record, $node, DOMXPath $xpath) {
  $node->type = 'regulation';

  // Date fields.
  if (($issuedNode = $xpath->query('.//dcterms:issued', $record)->item(0)) && trim($issuedNode->nodeValue) != '') {
    $node->field_reg_issued = array(
      LANGUAGE_NONE => array(array('value' => $issuedNode->nodeValue))
    );
  }

  // Text fields.
  if (($introNode = $xpath->query('.//dcterms:subject', $record)->item(0)) && !empty($introNode->nodeValue)) {
    $node->field_intro = array(
      LANGUAGE_NONE => array(array('value' => $introNode->nodeValue))
    );
  }
  $node->field_ratified_by = array(
    LANGUAGE_NONE => array(array('value' => $xpath->query('.//dcterms:isRatifiedBy', $record)->item(0)->nodeValue))
  );
  $node->field_reg_concerning = array(
    LANGUAGE_NONE => array(array('value' => $xpath->query('.//overheidrg:betreft', $record)->item(0)->nodeValue))
  );
  $node->field_reg_characteristic = array(
    LANGUAGE_NONE => array(array('value' => $xpath->query('.//overheidrg:kenmerk', $record)->item(0)->nodeValue))
  );
  $node->field_reg_subject = array(
    LANGUAGE_NONE => array(array('value' => $xpath->query('.//overheidrg:onderwerp', $record)->item(0)->nodeValue))
  );

  // Text fields with format.
  $node->field_red_addition = array(
    LANGUAGE_NONE => array(
      array(
        'value' => $xpath->query('.//overheidrg:redactioneleToevoeging', $record)->item(0)->nodeValue,
        'format' => 'filtered_html',
      )
    )
  );

  if (module_exists('scheduler')) {
    $publish_on_str = $xpath->query('.//overheidrg:inwerkingtredingDatum', $record)->item(0)->nodeValue;
    if (!empty($publish_on_str)) {
      $node->publish_on =  strtotime($publish_on_str);
    }

    $unpublish_on_str = $xpath->query('.//overheidrg:uitwerkingtredingDatum', $record)->item(0)->nodeValue;
    if (!empty($unpublish_on_str)) {
      $node->unpublish_on = strtotime($unpublish_on_str);
    }
  }

  // @todo, publicatieurl_xml
}