<?php
/**
 * Implements hook_permission().
 */
function gvop_permission() {
  return array(
    'administer gvop settings' => array(
      'title' => t('Administer gvop settings'),
      'description' => t('Allows users to configure GVOP settings.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function gvop_menu() {
  $items = array();

  $items['admin/config/content/gvop'] = array(
    'access arguments' => array('administer gvop settings'),
    'page arguments' => array('gvop_admin_settings_form'),
    'page callback' => 'drupal_get_form',
    'file' => 'gvop.admin.inc',
    'title' => 'GVOP',
    'description' => 'Configure GVOP settings.',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_cron().
 */
function gvop_cron() {
  $last_run = variable_get('gvop_cron_last_run', 0);
  $modified_str = 'modified>' . date('Y-m-d', $last_run);

  $gvop_info = module_invoke_all('gvop_info');
  foreach ($gvop_info as $type_info) {
    // Get count
    $dom = _gvop_retrieve_dom($type_info, 0, 1, array($modified_str));
    $num_results = (int) $dom->getElementsByTagName('numberOfRecords')->item(0)->nodeValue;
    $i = 0;

    while ($i < $num_results) {
      $dom = _gvop_retrieve_dom($type_info, $i, variable_get('gvop_limit', 20), array($modified_str));
      $xpath = new DOMXPath($dom);
      $records = $dom->getElementsByTagName("gzd");

      foreach ($records as $record) {
        $node = _gvop_map_node($type_info, $record, $xpath, TRUE);
        $i++;
      }
    }
  }

  variable_set('gvop_cron_last_run', time());
}

/**
 * Helper function to retrieve the uri for requesting.
 *
 * @param $start
 * @param $limit
 * @return string
 */
function _gvop_build_uri($type_info, $start, $limit, $params = array()) {
  $uri = variable_get('gvop_uri', 'https://zoek.officielebekendmakingen.nl/sru/Search');
  $query = array(
    'version' => '1.2',
    'operation' => 'searchRetrieve',
    'x-connection' => $type_info['type'],
    'startRecord' => $start,
    'maximumRecords' => $limit,
    'query' =>
    'creator==' . variable_get('gvop_creator', '')
  );
  foreach ($type_info['query'] as $key => $value) {
    $query['query'] .= ' and ' . $key . '==' . $value;
  }
  foreach ($params as $param) {
    $query['query'] .= ' and ' . $param;
  }
  return $uri . '?' . drupal_http_build_query($query);
}

/**
 * Helper function to retrieve the DOMDocument.
 *
 * @param $start
 * @param $limit
 * @return DOMDocument
 */
function _gvop_retrieve_dom($type_info, $start, $limit, $params = array()) {
  $uri = _gvop_build_uri($type_info, $start, $limit, $params);
  $data = drupal_http_request($uri);
  if ($data->code != 200) {
    // @todo, add error reporting for HTTP request and Diagnose response
  }
  else {
    $dom = new DOMDocument();
    $dom->loadXML($data->data);
  }
  return $dom;
}

/**
 * Function to map a gvop node.
 *
 * @param $type_info
 * @param DOMElement $record
 * @param DOMXPath $xpath
 * @param bool $force
 * @return bool|mixed|stdClass
 */
function _gvop_map_node($type_info, DOMElement $record, DOMXPath $xpath, $force = FALSE) {
  $identifier = $xpath->query('.//dcterms:identifier', $record)->item(0)->nodeValue;

  // Get the current version from the database.
  $current = db_select('gvop', 'g')
    ->fields('g', array('identifier', 'hash', 'nid'))
    ->condition('identifier', $identifier)
    ->execute()
    ->fetchAssoc();

  // Generate an hash for checking the update.
  $xml = $record->ownerDocument->saveXML($record);
  $xml_hash = md5($xml);

  // Is this an actual update.
  if (!$force && $current && $xml_hash == $current['hash']) {
    return FALSE;
  }

  // Are we updating or inserting.
  $modified = strtotime($xpath->query('.//dcterms:modified', $record)->item(0)->nodeValue);
  if ($current && !empty($current['nid'])) {
    $node = node_load($current['nid']);
  }
  else {
    $node = new stdClass();
    $node->uid = 1;
    $node->created = $modified;
    $node->type = $type_info['nodetype'];
  }

  // Set common info.
  $node->gvop_identifier = $identifier;
  $node->title = substr($xpath->query('.//dcterms:title', $record)->item(0)->nodeValue, 0, 255);
  $node->changed = $modified;

  // Run the callback for mapping this type.
  $type_info['callback']($record, $node, $xpath);

  node_save($node);

  // Add to the GVOP table for hash checking and identifying.
  db_merge('gvop')
    ->key(array('identifier' => $identifier))
    ->fields(array('hash' => $xml_hash, 'nid' => $node->nid, 'xml' => $xml, 'changed' => REQUEST_TIME))
    ->execute();

  return $node;
}

/**
 * Implements hook_node_delete().
 */
function gvop_node_delete($node) {
  $nodetypes = array();
  $gvop_info = module_invoke_all('gvop_info');
  foreach ($gvop_info as $type_info) {
    $nodetypes[] = $type_info['nodetype'];
  }
  if (in_array($node->type, $nodetypes)) {
    db_delete('gvop')->condition('nid', $node->nid)->execute();
  }
}
