<?php

/**
 * Implements hook_page_build().
 */
function dimpact_kcmsurvey_page_build(&$page) {
  // Adding attachments to an element of type page does not work, because then
  // the html theme_wrapper runs before attachments processing.
  // The page template does render regions, so page attachments can be added there.
  if (!isset($page['page_bottom'])) {
    $page['page_bottom'] = array();
  }
  _dimpact_kcmsurvey_page_bottom($page['page_bottom']);
}

function _dimpact_kcmsurvey_page_bottom(array &$page_bottom) {
  $page_attachments = array();
  _dimpact_kcmsurvey_page_attachments($page_attachments);
  $page_bottom['dimpact_kcmsurvey_page_attachments'] = $page_attachments;
}

function _dimpact_kcmsurvey_page_attachments(array &$page) {
  $dimpact_kcmsurvey_script_url = variable_get('dimpact_kcmsurvey_script_url');
  if ($dimpact_kcmsurvey_script_url) {
    if (module_exists('domain')) {
      $domain = domain_get_domain();
      // @todo Document why we seek a "main domain" instead of the default domain.
      $main_domain = $domain['domain_id'] == 1 ?: FALSE;
    } else {
      $main_domain = TRUE;
    }
    if ($main_domain && !drupal_is_front_page()) {
      $page['#attached']['js'][$dimpact_kcmsurvey_script_url] = array('type' => 'external');
    }
  }
}
