<?php

/**
 * Implements hook_menu().
 */
function dimpact_siteimprove_menu() {
  $items = array();

  $items['admin/config/system/siteimprove'] = array(
    'title' => 'Siteimprove',
    'description' => 'Siteimprove settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('siteimprove_admin_settings_form'),
    'access arguments' => array('administer siteimprove'),
    'file' => 'dimpact_siteimprove.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_permisison().
 */
function dimpact_siteimprove_permission() {
  return array(
    'administer siteimprove' => array(
      'title' => t('Administer Siteimprove'),
      'description' => t('Used to configure the Siteimprove account ID.'),
    ),
  );
}

/**
 * Implements hook_page_build().
 */
function dimpact_siteimprove_page_build(&$page) {
  // Adding attachments to an element of type page does not work, because then
  // the html theme_wrapper runs before attachments processing.
  // The page template does render regions, so page attachments can be added there.
  if (!isset($page['page_bottom'])) {
    $page['page_bottom'] = array();
  }

  _dimpact_siteimprove_page_bottom($page['page_bottom']);
}

function _dimpact_siteimprove_page_bottom(array &$page_bottom) {
  global $theme_key;
  drupal_theme_initialize();

  // Deny access if admin theme is active.
  if ($theme_key == variable_get('admin_theme') || variable_get('dimpact_siteimprove_id', '') === '') {
    $access = FALSE;
  } else {
    $access = TRUE;
  }

  $data = "<script>
              //<![CDATA[
               (function() {
                 var sz = document.createElement('script');
                     sz.type = 'text/javascript';
                     sz.async = true;
                     sz.src = '//ssl.siteimprove.com/js/siteanalyze_" . variable_get('dimpact_siteimprove_id') . ".js';
                 var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(sz, s);
                }) ();
               //]]>
           </script>";

  $page_bottom['dimpact_siteimprove_page_attachments'] = array(
    '#type' => 'markup',
    '#markup' => $data,
    '#access' => $access,
  );
}
