<?php

/**
 * Implements hook_permission().
 */
function durp_permission() {
  return array(
    'start durp import' => array(
      'title' => t('Start Durp import'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function durp_menu() {
  $items = array();

  $items['admin/config/content/durp'] = array(
    'title' => 'DURP',
    'description' => 'Durp import settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('durp_admin_settings_form'),
    'access arguments' => array('start durp import'),
    'file' => 'durp.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_node_delete().
 */
function durp_node_delete($node) {
  db_delete('durp')->condition('nid', $node->nid)->execute();
}

/**
 * Implements hook_cron().
 */
function durp_cron() {
  module_load_include('inc', 'durp', 'durp.import');
  durp_import_batch_start();
}
