<?php
/**
 * Implements hook_permission().
 */
function solr_synonyms_permission() {
  return array(
    'administer solr_synonyms settings' => array(
      'title' => t('Administer solr_synonyms settings'),
      'description' => t('Allows users to configure solr_synonyms settings.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function solr_synonyms_menu() {
  $items = array();

  $items['admin/config/search/apachesolr/synonyms'] = array(
    'access arguments' => array('administer solr_synonyms settings'),
    'page arguments' => array('solr_synonyms_admin_settings_form'),
    'page callback' => 'drupal_get_form',
    'title' => 'Solr Synonyms',
    'description' => 'Configure solr_synonyms settings.',
    'type' => MENU_LOCAL_TASK,
    'file' => 'solr_synonyms.admin.inc',
  );

  $items['admin/config/search/apachesolr/synonyms/delete/%'] = array(
    'access arguments' => array('administer solr_synonyms settings'),
    'page arguments' => array('solr_synonyms_admin_settings_delete_form', 6),
    'page callback' => 'drupal_get_form',
    'type' => MENU_CALLBACK,
    'file' => 'solr_synonyms.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function solr_synonyms_theme($existing, $type, $theme, $path) {
  return array(
    'solr_synonyms_table_synonyms' => array(
      'arguments' => array(
        'form' => NULL
      ),
      'render element' => 'synonyms',
      'file' => 'solr_synonyms.admin.inc',
    ),
  );
}