<?php
/**
 * @file
 * dimpact_alphabet_menus.features.menu_custom.inc
 */

/**
 * Implements hook_menu_default_menu_custom().
 */
function dimpact_alphabet_menus_menu_default_menu_custom() {
  $menus = array();

  // Exported menu: menu-alfabet.
  $menus['menu-alfabet'] = array(
    'menu_name' => 'menu-alfabet',
    'title' => 'Alfabet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-a.
  $menus['menu-alfabet-a'] = array(
    'menu_name' => 'menu-alfabet-a',
    'title' => 'Alfabet A',
    'description' => '',
  );
  // Exported menu: menu-alfabet-a-intranet.
  $menus['menu-alfabet-a-intranet'] = array(
    'menu_name' => 'menu-alfabet-a-intranet',
    'title' => 'Alfabet A intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-b.
  $menus['menu-alfabet-b'] = array(
    'menu_name' => 'menu-alfabet-b',
    'title' => 'Alfabet B',
    'description' => '',
  );
  // Exported menu: menu-alfabet-b-intranet.
  $menus['menu-alfabet-b-intranet'] = array(
    'menu_name' => 'menu-alfabet-b-intranet',
    'title' => 'Alfabet B intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-c.
  $menus['menu-alfabet-c'] = array(
    'menu_name' => 'menu-alfabet-c',
    'title' => 'Alfabet C',
    'description' => '',
  );
  // Exported menu: menu-alfabet-c-intranet.
  $menus['menu-alfabet-c-intranet'] = array(
    'menu_name' => 'menu-alfabet-c-intranet',
    'title' => 'Alfabet C intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-d.
  $menus['menu-alfabet-d'] = array(
    'menu_name' => 'menu-alfabet-d',
    'title' => 'Alfabet D',
    'description' => '',
  );
  // Exported menu: menu-alfabet-d-intranet.
  $menus['menu-alfabet-d-intranet'] = array(
    'menu_name' => 'menu-alfabet-d-intranet',
    'title' => 'Alfabet D intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-e.
  $menus['menu-alfabet-e'] = array(
    'menu_name' => 'menu-alfabet-e',
    'title' => 'Alfabet E',
    'description' => '',
  );
  // Exported menu: menu-alfabet-e-intranet.
  $menus['menu-alfabet-e-intranet'] = array(
    'menu_name' => 'menu-alfabet-e-intranet',
    'title' => 'Alfabet E intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-f.
  $menus['menu-alfabet-f'] = array(
    'menu_name' => 'menu-alfabet-f',
    'title' => 'Alfabet F',
    'description' => '',
  );
  // Exported menu: menu-alfabet-f-intranet.
  $menus['menu-alfabet-f-intranet'] = array(
    'menu_name' => 'menu-alfabet-f-intranet',
    'title' => 'Alfabet F intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-g.
  $menus['menu-alfabet-g'] = array(
    'menu_name' => 'menu-alfabet-g',
    'title' => 'Alfabet G',
    'description' => '',
  );
  // Exported menu: menu-alfabet-g-intranet.
  $menus['menu-alfabet-g-intranet'] = array(
    'menu_name' => 'menu-alfabet-g-intranet',
    'title' => 'Alfabet G intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-h.
  $menus['menu-alfabet-h'] = array(
    'menu_name' => 'menu-alfabet-h',
    'title' => 'Alfabet H',
    'description' => '',
  );
  // Exported menu: menu-alfabet-h-intranet.
  $menus['menu-alfabet-h-intranet'] = array(
    'menu_name' => 'menu-alfabet-h-intranet',
    'title' => 'Alfabet H intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-i.
  $menus['menu-alfabet-i'] = array(
    'menu_name' => 'menu-alfabet-i',
    'title' => 'Alfabet I',
    'description' => '',
  );
  // Exported menu: menu-alfabet-i-intranet.
  $menus['menu-alfabet-i-intranet'] = array(
    'menu_name' => 'menu-alfabet-i-intranet',
    'title' => 'Alfabet I intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-j.
  $menus['menu-alfabet-j'] = array(
    'menu_name' => 'menu-alfabet-j',
    'title' => 'Alfabet J',
    'description' => '',
  );
  // Exported menu: menu-alfabet-j-intranet.
  $menus['menu-alfabet-j-intranet'] = array(
    'menu_name' => 'menu-alfabet-j-intranet',
    'title' => 'Alfabet J intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-k.
  $menus['menu-alfabet-k'] = array(
    'menu_name' => 'menu-alfabet-k',
    'title' => 'Alfabet K',
    'description' => '',
  );
  // Exported menu: menu-alfabet-k-intranet.
  $menus['menu-alfabet-k-intranet'] = array(
    'menu_name' => 'menu-alfabet-k-intranet',
    'title' => 'Alfabet K intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-l.
  $menus['menu-alfabet-l'] = array(
    'menu_name' => 'menu-alfabet-l',
    'title' => 'Alfabet L',
    'description' => '',
  );
  // Exported menu: menu-alfabet-l-intranet.
  $menus['menu-alfabet-l-intranet'] = array(
    'menu_name' => 'menu-alfabet-l-intranet',
    'title' => 'Alfabet L intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-m.
  $menus['menu-alfabet-m'] = array(
    'menu_name' => 'menu-alfabet-m',
    'title' => 'Alfabet M',
    'description' => '',
  );
  // Exported menu: menu-alfabet-m-intranet.
  $menus['menu-alfabet-m-intranet'] = array(
    'menu_name' => 'menu-alfabet-m-intranet',
    'title' => 'Alfabet M intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-n.
  $menus['menu-alfabet-n'] = array(
    'menu_name' => 'menu-alfabet-n',
    'title' => 'Alfabet N',
    'description' => '',
  );
  // Exported menu: menu-alfabet-n-intranet.
  $menus['menu-alfabet-n-intranet'] = array(
    'menu_name' => 'menu-alfabet-n-intranet',
    'title' => 'Alfabet N intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-o.
  $menus['menu-alfabet-o'] = array(
    'menu_name' => 'menu-alfabet-o',
    'title' => 'Alfabet O',
    'description' => '',
  );
  // Exported menu: menu-alfabet-o-intranet.
  $menus['menu-alfabet-o-intranet'] = array(
    'menu_name' => 'menu-alfabet-o-intranet',
    'title' => 'Alfabet O intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-p.
  $menus['menu-alfabet-p'] = array(
    'menu_name' => 'menu-alfabet-p',
    'title' => 'Alfabet P',
    'description' => '',
  );
  // Exported menu: menu-alfabet-p-intranet.
  $menus['menu-alfabet-p-intranet'] = array(
    'menu_name' => 'menu-alfabet-p-intranet',
    'title' => 'Alfabet P intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-q.
  $menus['menu-alfabet-q'] = array(
    'menu_name' => 'menu-alfabet-q',
    'title' => 'Alfabet Q',
    'description' => '',
  );
  // Exported menu: menu-alfabet-q-intranet.
  $menus['menu-alfabet-q-intranet'] = array(
    'menu_name' => 'menu-alfabet-q-intranet',
    'title' => 'Alfabet Q intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-r.
  $menus['menu-alfabet-r'] = array(
    'menu_name' => 'menu-alfabet-r',
    'title' => 'Alfabet R',
    'description' => '',
  );
  // Exported menu: menu-alfabet-r-intranet.
  $menus['menu-alfabet-r-intranet'] = array(
    'menu_name' => 'menu-alfabet-r-intranet',
    'title' => 'Alfabet R intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-s.
  $menus['menu-alfabet-s'] = array(
    'menu_name' => 'menu-alfabet-s',
    'title' => 'Alfabet S',
    'description' => '',
  );
  // Exported menu: menu-alfabet-s-intranet.
  $menus['menu-alfabet-s-intranet'] = array(
    'menu_name' => 'menu-alfabet-s-intranet',
    'title' => 'Alfabet S intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-t.
  $menus['menu-alfabet-t'] = array(
    'menu_name' => 'menu-alfabet-t',
    'title' => 'Alfabet T',
    'description' => '',
  );
  // Exported menu: menu-alfabet-t-intranet.
  $menus['menu-alfabet-t-intranet'] = array(
    'menu_name' => 'menu-alfabet-t-intranet',
    'title' => 'Alfabet T intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-u.
  $menus['menu-alfabet-u'] = array(
    'menu_name' => 'menu-alfabet-u',
    'title' => 'Alfabet U',
    'description' => '',
  );
  // Exported menu: menu-alfabet-u-intranet.
  $menus['menu-alfabet-u-intranet'] = array(
    'menu_name' => 'menu-alfabet-u-intranet',
    'title' => 'Alfabet U intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-v.
  $menus['menu-alfabet-v'] = array(
    'menu_name' => 'menu-alfabet-v',
    'title' => 'Alfabet V',
    'description' => '',
  );
  // Exported menu: menu-alfabet-v-intranet.
  $menus['menu-alfabet-v-intranet'] = array(
    'menu_name' => 'menu-alfabet-v-intranet',
    'title' => 'Alfabet V intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-w.
  $menus['menu-alfabet-w'] = array(
    'menu_name' => 'menu-alfabet-w',
    'title' => 'Alfabet W',
    'description' => '',
  );
  // Exported menu: menu-alfabet-w-intranet.
  $menus['menu-alfabet-w-intranet'] = array(
    'menu_name' => 'menu-alfabet-w-intranet',
    'title' => 'Alfabet W intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-x.
  $menus['menu-alfabet-x'] = array(
    'menu_name' => 'menu-alfabet-x',
    'title' => 'Alfabet X',
    'description' => '',
  );
  // Exported menu: menu-alfabet-x-intranet.
  $menus['menu-alfabet-x-intranet'] = array(
    'menu_name' => 'menu-alfabet-x-intranet',
    'title' => 'Alfabet X intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-y.
  $menus['menu-alfabet-y'] = array(
    'menu_name' => 'menu-alfabet-y',
    'title' => 'Alfabet Y',
    'description' => '',
  );
  // Exported menu: menu-alfabet-y-intranet.
  $menus['menu-alfabet-y-intranet'] = array(
    'menu_name' => 'menu-alfabet-y-intranet',
    'title' => 'Alfabet Y intranet',
    'description' => '',
  );
  // Exported menu: menu-alfabet-z.
  $menus['menu-alfabet-z'] = array(
    'menu_name' => 'menu-alfabet-z',
    'title' => 'Alfabet Z',
    'description' => '',
  );
  // Exported menu: menu-alfabet-z-intranet.
  $menus['menu-alfabet-z-intranet'] = array(
    'menu_name' => 'menu-alfabet-z-intranet',
    'title' => 'Alfabet Z intranet',
    'description' => '',
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('Alfabet');
  t('Alfabet A');
  t('Alfabet A intranet');
  t('Alfabet B');
  t('Alfabet B intranet');
  t('Alfabet C');
  t('Alfabet C intranet');
  t('Alfabet D');
  t('Alfabet D intranet');
  t('Alfabet E');
  t('Alfabet E intranet');
  t('Alfabet F');
  t('Alfabet F intranet');
  t('Alfabet G');
  t('Alfabet G intranet');
  t('Alfabet H');
  t('Alfabet H intranet');
  t('Alfabet I');
  t('Alfabet I intranet');
  t('Alfabet J');
  t('Alfabet J intranet');
  t('Alfabet K');
  t('Alfabet K intranet');
  t('Alfabet L');
  t('Alfabet L intranet');
  t('Alfabet M');
  t('Alfabet M intranet');
  t('Alfabet N');
  t('Alfabet N intranet');
  t('Alfabet O');
  t('Alfabet O intranet');
  t('Alfabet P');
  t('Alfabet P intranet');
  t('Alfabet Q');
  t('Alfabet Q intranet');
  t('Alfabet R');
  t('Alfabet R intranet');
  t('Alfabet S');
  t('Alfabet S intranet');
  t('Alfabet T');
  t('Alfabet T intranet');
  t('Alfabet U');
  t('Alfabet U intranet');
  t('Alfabet V');
  t('Alfabet V intranet');
  t('Alfabet W');
  t('Alfabet W intranet');
  t('Alfabet X');
  t('Alfabet X intranet');
  t('Alfabet Y');
  t('Alfabet Y intranet');
  t('Alfabet Z');
  t('Alfabet Z intranet');


  return $menus;
}
