<?php

/**
 * Implements hook_entity_info_alter().
 */
function bespoke_entity_info_alter(&$entity_info) {
  $entity_info['file']['view modes']['overig_onderwerp'] = array(
    'label' => t('Overig onderwerp'),
    'custom settings' => TRUE,
  );

  $entity_info['file']['view modes']['slide_93'] = array(
    'label' => t('Carrousel slide 9/3'),
    'custom settings' => TRUE,
  );

  $entity_info['file']['view modes']['banner'] = array(
    'label' => t('Banner'),
    'custom settings' => TRUE,
  );

  $entity_info['file']['view modes']['origineel'] = array(
    'label' => t('Origineel'),
    'custom settings' => TRUE,
  );

  $entity_info['file']['view modes']['volle_breedte'] = array(
    'label' => t('Volle breedte'),
    'custom settings' => TRUE,
  );

  $entity_info['file']['view modes']['portret'] = array(
    'label' => t('Portret'),
    'custom settings' => TRUE,
  );

  $entity_info['node']['view modes']['volle_breedte'] = array(
    'label' => t('Volle breedte'),
    'custom settings' => TRUE,
  );
}


function bespoke_module_implements_alter(&$data, $hook) {
  if ($hook == 'page_alter') {
    // We have a custom check whether or not to show piwik/ga. So this is
    // handled in bespoke_page_alter().
    unset($data['piwik']);
    unset($data['googleanalytics']);
  }
}

function bespoke_page_alter(&$page) {
  if (dominion_has_function('piwik') && module_exists('piwik')) {
    piwik_page_alter($page);
  }
  if (dominion_has_function('googleanalytics') && module_exists('googleanalytics')) {
    googleanalytics_page_alter($page);
  }
}