<?php
/**
* Implements hook_form_FORM_ID_alter().
*/
function domain_scss_form_system_theme_settings_alter(&$form, &$form_state) {
  if (isset($form_state['build_info']['args'][0]) && ($theme = $form_state['build_info']['args'][0]) && domain_scss_get_info($theme)) {
    $form['color'] = array(
      '#type' => 'fieldset',
      '#title' => t('Color scheme'),
      '#weight' => -1,
      '#attributes' => array('id' => 'color_scheme_form'),
      '#theme' => 'color_scheme_form',
    );
    $form['color'] += domain_scss_scheme_form($form, $form_state, $theme);
    $form['#validate'][] = 'color_scheme_form_validate';
    $form['#submit'][] = 'domain_scss_scheme_form_submit';
  }
}

/**
 * Retrieves the Domain SCSS module information for a particular theme.
 */
function domain_scss_get_info($theme) {
  static $theme_info = array();

  if (isset($theme_info[$theme])) {
    return $theme_info[$theme];
  }

  $path = drupal_get_path('theme', $theme);
  $file = DRUPAL_ROOT . '/' . $path . '/domain_scss/domain_scss.inc';
  if ($path && file_exists($file)) {
    include $file;
    $theme_info[$theme] = $info;
    return $info;
  }
}

/**
 * Form constructor for the color configuration form for a particular theme.
 *
 * @param $theme
 *   The machine name of the theme whose color settings are being configured.
 *
 * @see color_scheme_form_validate()
 * @see color_scheme_form_submit()
 * @ingroup forms
 */
function domain_scss_scheme_form($complete_form, &$form_state, $theme) {
  $color_base = drupal_get_path('module', 'color');
  $info = domain_scss_get_info($theme);

  $info['schemes'][''] = array('title' => t('Custom'), 'colors' => array());
  $color_sets = array();
  $schemes = array();
  foreach ($info['schemes'] as $key => $scheme) {
    $color_sets[$key] = $scheme['title'];
    $schemes[$key] = $scheme['colors'];
    $schemes[$key] += $info['schemes']['default']['colors'];
  }

  // See if we're using a predefined scheme.
  // Note: we use the original theme when the default scheme is chosen.
  $current_scheme = variable_get('color_' . $theme . '_palette', array());
  foreach ($schemes as $key => $scheme) {
    if ($current_scheme == $scheme) {
      $scheme_name = $key;
      break;
    }
  }
  if (empty($scheme_name)) {
    if (empty($current_scheme)) {
      $scheme_name = 'default';
    }
    else {
      $scheme_name = '';
    }
  }

  // Add scheme selector.
  $form['scheme'] = array(
    '#type' => 'select',
    '#title' => t('Color set'),
    '#options' => $color_sets,
    '#default_value' => $scheme_name,
    '#attached' => array(
      // Add Farbtastic color picker.
      'library' => array(
        array('system', 'farbtastic'),
      ),
      // Add custom CSS.
      'css' => array(
        $color_base . '/color.css' => array(),
      ),
      // Add custom JavaScript.
      'js' => array(
        $color_base . '/color.js',
        array(
          'data' => array(
            'color' => array(
              'reference' => domain_scss_get_palette($theme, TRUE),
              'schemes' => $schemes,
            ),
          ),
          'type' => 'setting',
        ),
      ),
    ),
  );

  // Add palette fields.
  $palette = domain_scss_get_palette($theme);
  $names = $info['fields'];
  $form['palette']['#tree'] = TRUE;
  foreach ($palette as $name => $value) {
    if (isset($names[$name])) {
      $form['palette'][$name] = array(
        '#type' => 'textfield',
        '#title' => check_plain($names[$name]),
        '#default_value' => $value,
        '#size' => 8,
      );
    }
  }
  $form['theme'] = array('#type' => 'value', '#value' => $theme);
  $form['info'] = array('#type' => 'value', '#value' => $info);

  return $form;
}

/**
 * Retrieves the color palette for a particular theme.
 */
function domain_scss_get_palette($theme, $default = FALSE) {
  // Fetch and expand default palette.
  $info = domain_scss_get_info($theme);
  $palette = $info['schemes']['default']['colors'];

  // Load variable.
  return $default ? $palette : variable_get('color_' . $theme . '_palette', $palette);
}

/**
 * Form submission handler for color_scheme_form().
 *
 * @see color_scheme_form_validate()
 */
function domain_scss_scheme_form_submit($form, &$form_state) {
  // Get theme coloring info.
  if (!isset($form_state['values']['info'])) {
    return;
  }
  $theme = $form_state['values']['theme'];
  $info = $form_state['values']['info'];

  drupal_set_message('New stylesheet has been compiled for ' . $theme);

  // Resolve palette.
  $palette = $form_state['values']['palette'];
  if ($form_state['values']['scheme'] != '') {
    foreach ($palette as $key => $color) {
      if (isset($info['schemes'][$form_state['values']['scheme']]['colors'][$key])) {
        $palette[$key] = $info['schemes'][$form_state['values']['scheme']]['colors'][$key];
      }
    }
    $palette += $info['schemes']['default']['colors'];
  }

  // Delete old setup.
  if ($old_dir = variable_get('color_' . $theme . '_files', FALSE)) {
    file_unmanaged_delete_recursive($old_dir);
  }
  variable_del('color_' . $theme . '_palette');
  variable_del('color_' . $theme . '_stylesheets');
  variable_del('color_' . $theme . '_files');

  // Prepare target locations for generated files.
  $id = $theme . '-' . substr(hash('sha256', serialize($palette) . microtime()), 0, 8);
  $paths['color'] = 'public://color';
  $paths['target'] = $paths['color'] . '/' . $id;
  foreach ($paths as $path) {
    file_prepare_directory($path, FILE_CREATE_DIRECTORY);
  }

  $css_dir = drupal_realpath($paths['target']);
  $theme_dir = DRUPAL_ROOT . '/'. drupal_get_path('theme', $theme);

  $cmd = "compass compile --boring --css-dir $css_dir $theme_dir;";
  foreach ($palette as $key => $value) {
    $key = 'DOMAIN_SCSS_' . $key;

    $cmd = 'export ' . $key . '=' . $value . '; ' . $cmd;
    $cmd = $cmd . ' unset ' . $key . ';';
  }

  $output = shell_exec($cmd);

  watchdog('domain_scss', "Generated css <pre>!cmd\n\n !output</pre>", array('!cmd' => $cmd, '!output' => $output), WATCHDOG_INFO);

  $css = array();
  foreach ($info['css'] as $css_file) {
    $css[] = $paths['target'] . '/' . $css_file;
  }

  // Save data.
  variable_set('color_' . $theme . '_palette', $palette);
  variable_set('color_' . $theme . '_files', $paths['target']);
  variable_set('color_' . $theme . '_stylesheets', $css);
}