<?php
define('RSS_BLOCKS_DEFAULT_HOMEBOX_PAGE', 'dashboard_intranet');

/**
 * Implements hook_block_info().
 */
function rss_blocks_block_info() {
  $feeds = db_select('node', 'n')
    ->fields('n', array('nid', 'title'))
    ->condition('status', 1)
    ->condition('type', 'rss_source')
    ->execute();

  foreach ($feeds as $feed) {
    $blocks[$feed->nid] = array(
      'info' => t('RSS Feed: !feed', array('!feed' => $feed->title)),
      'cache' => DRUPAL_NO_CACHE,
    );
  }

  return $blocks;
}

/**
 * Impelements hook_block_view().
 */
function rss_blocks_block_view($delta) {
  $feed_node = node_load($delta);

  return array(
    'subject' => $feed_node->title,
    'content' => views_embed_view('feeds_intranet', 'block_1', $feed_node->nid),
  );
}

/**
 * Implements hook_node_insert().
 */
function rss_blocks_node_insert($node) {
  if ($node->type == 'rss_source') {
    _rss_blocks_homebox_add($node);
    block_flush_caches();
  }
}

/**
 * Implements hook_node_update().
 */
function rss_blocks_node_update($node) {
  if ($node->type == 'rss_source') {
    _rss_blocks_homebox_add($node);
    block_flush_caches();
  }
}

/**
 * Implements hook_node_delete().
 */
function rss_blocks_node_delete($node) {
  if ($node->type == 'rss_source') {
    _rss_blocks_homebox_remove($node);
    block_flush_caches();
  }
}

/**
 * Helper function for adding a block to homebox.
 */
function _rss_blocks_homebox_add($node) {
  if (module_exists('homebox')) {
    $page = homebox_get_page(variable_get('rss_blocks_homebox_page', RSS_BLOCKS_DEFAULT_HOMEBOX_PAGE));

    $page->settings['blocks']['rss_blocks_' . $node->nid] = array(
      'module' => 'rss_blocks',
      'delta' => $node->nid,
      'region' => 2,
      'movable' => 1,
      'status' => 1,
      'open' => 1,
      'closable' => 1,
      'title' => '',
      'weight' => 0,
    );

    homebox_save_page($page);
  }
}

/**
 * Helper function for removing a block from homebox.
 */
function _rss_blocks_homebox_remove($node) {
  if (module_exists('homebox')) {
    $page = homebox_get_page(variable_get('rss_blocks_homebox_page', RSS_BLOCKS_DEFAULT_HOMEBOX_PAGE));
    unset($page->settings['blocks']['rss_blocks-' . $node->nid]);
    homebox_save_page($page);
  }
}