<?php
/**
 * Implements hook_form_alter().
 */
function ris_ibabs_form_ris_admin_settings_form_alter(&$form, &$form_state) {
  $form['ris_settings']['ris_ibabs_dir'] = array(
    '#type' => 'textfield',
    '#title' => t('Corsa Directory'),
    '#default_value' => variable_get('ris_ibabs_dir', ''),
    '#description' => t('For example "/var/export/ibabs"'),
  );
}

/**
 * Implements hook_ris_info().
 */
function ris_ibabs_ris_info() {
  return array(
    'ris_ibabs' => array(
      'name' => 'ris_ibabs',
      'module' => 'ris_ibabs',
      'batch_file' => drupal_get_path('module', 'ris_ibabs') . '/ris_ibabs.import.inc',
      'batch_callback' => '_ris_ibabs_import_batch_run',
    ),
  );
}