<?php

/**
 * Implements hook_form_alter().
 */
function dimpact_service_links_form_alter(&$form, $form_state) {
	if ($form['#form_id'] == 'service_links_admin_settings') {
		$form['how_to_show_the_links']['dimpact_service_links_display_style'] = array(
	    '#type' => 'select',
	    '#title' => t('Service links display style'),
	    '#default_value' => variable_get('dimpact_service_links_display_style'),
	    '#options' => array(
	      0 => t('Plain'),
	      1 => t('Overlay'),
	    ),
	    '#description' => t('Select how the service links should be displayed, plain or in an overlay.'),
  	);

	return system_settings_form($form);
	}
}