<?php

/**
 * @file dimpact_docreader.module
 * docReader-implementatie voor Dimpact.
 * © Dutch Open Projects 2016.
 */

/**
 * List of file types currently supported by docReader (http://www.readspeaker.com/nl/readspeaker-docreader/)
 * ePub (.epub)
 * Microsoft Excel (.xls, .xlsx)
 * Microsoft PowerPoint (.pps, .ppt, .pptx)
 * Microsoft Word (.doc, .docx)
 * OpenOffice/OpenDocument presentatie (.odp)
 * OpenOffice/OpenDocument Spreadsheet (.ods)
 * OpenOffice/OpenDocument tekst (.odt)
 * Portable Document Format (.pdf)
 * Rich Text Format (.rtf)
 */
function docreader_supported_file_extensions() {
  return 'epub, xls, xlsx, pps, ppt, pptx, doc, docx, odp, ods, odt, pdf, rtf';
}

/**
 * Implements hook_permission().
 */
function dimpact_docreader_permission() {
  $permissions = array();
  $permissions['administer dimpact_docreader'] = array(
    'title' => t('Dimpact docReader Instellingen'),
    'description' => t('Toegangsrechten voor de instellingenpagina van de Dimpact docReader-module.'),
  );

  return $permissions;
}

/**
 * Implements hook_menu().
 */
function dimpact_docreader_menu() {
  $items = array();
  $items['admin/config/dimpact_docreader'] = array(
    'title' => 'Dimpact docReader Instellingen',
    'description' => 'Dit is de instellingenpagina voor de Dimpact docReader-module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dimpact_docreader_settings_form'),
    'access arguments' => array('administer dimpact_docreader'),
    'file' => 'dimpact_docreader.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_page_build().
 */
function dimpact_docreader_page_build(&$page) {
  // Adding attachments to an element of type page does not work, because then
  // the html theme_wrapper runs before attachments processing.
  // The page template does render regions, so page attachments can be added there.
  if (!isset($page['page_bottom'])) {
    $page['page_bottom'] = array();
  }

  _dimpact_docreader_page_bottom($page['page_bottom']);
}

function _dimpact_docreader_page_bottom(array &$page_bottom) {
  global $theme_key;
  drupal_theme_initialize();

  // Deny access if admin theme is active or no docReader customer id is set.
  if ($theme_key == variable_get('admin_theme') || variable_get('dimpact_docreader_cid') === NULL) {
    $access = FALSE;
  } else {
    $access = TRUE;
  }

  $new_lines_and_spaces_regexp = '/[\r\n\s]/';

  $data = "<script type=\"text/javascript\">
              //<![CDATA[
               (function() {
                 var links = document.getElementsByTagName('a');
                 var cid = '". variable_get('dimpact_docreader_cid') ."';
                 var language = '" . variable_get('dimpact_docreader_language', 'nl_nl') . "';
                 var url = '';
                 var supported_file_extensions = '" . preg_replace( $new_lines_and_spaces_regexp, '', variable_get( 'dimpact_docreader_supported_file_extensions' ) ) . "'.split(',');
                 var supported_domains = '"         . preg_replace( $new_lines_and_spaces_regexp, '', variable_get( 'dimpact_docreader_supported_domains' ) ) . "'.split(',');
                 for (var i = 0; i < links.length; i++) {
                    var match_extension_regexp = new RegExp( /\.([a-z0-9]+)$/, 'i' );
                    
                    if ( match_extension_regexp.test( links[i].href ) === true ) {
                      var extension = links[i].href.match( match_extension_regexp )[1];
                    } else if ( match_extension_regexp.test( links[i].text ) === true ) {
                      var extension = links[i].text.match( match_extension_regexp )[1];
                    } else {
                      // No extension found. Continue with the next iteration.
                      continue;
                    }
                    
                    if ( supported_file_extensions.indexOf( extension ) !== -1 ) {
                      // Some-loop-routine to make wild card testing possible.
                      // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some
                      supported_domains.some( function( supported_domain ) {
                        // Prepare string for regexp.
                        // Escape dots + turn wild cards into '.*'.
                        var supported_domain_regexp_string = supported_domain.replace( /\./g, '\\.' ).replace( '*', '.*' );
                        
                        var supported_domain_regexp = new RegExp( supported_domain_regexp_string, 'i' );
                        var host = links[i].host; // E.g. 'www.example.com'.
                        if ( supported_domain_regexp.test( host ) === true ) {
                          url = encodeURIComponent(links[i].href);
                          links[i].insertAdjacentHTML( 'afterend', ' <a rel=\"nofollow\" class=\"docreader\" title=\"" . t('Lees voor') . "\" href=\"http://docreader.readspeaker.com/docreader/?cid=' + cid + '&lang=' + language + '&url=' + url + '\" onclick=\"window.open(this.href); return false\"><img src=\"/" . drupal_get_path('module', 'dimpact_docreader') . "/images/docreader_icon.gif\" /> " . t('Lees voor') . "</a> ' );
                          i++; // Prevents the creation of docReader links on docReader links ad infinitum.  
                          return true; // Match found, return from loop (continue).
                        }
                      });
                    }
                 }
               }) ();
              //]]>
           </script>";

  $page_bottom['dimpact_docreader_page_attachments'] = array(
    '#type' => 'markup',
    '#markup' => $data,
    '#access' => $access,
  );
}
